image: alpine:latest

pages:
  stage: deploy
  script:
    - '[ -d public ] || mkdir public'
    - apk add --no-cache rsync
    - rsync -av --exclude='public' . public/
  artifacts:
    paths:
      - public
  only:
    - master